# Generated by Django 4.2.13 on 2024-06-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='xcerpt',
            new_name='excerpt',
        ),
    ]
